name: Build and Publish VM Image

on:
  push:
    branches:
      - main

env:
  PRODUCT_VERSION: "1.8.6"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    name: run packer
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ vars.WL_IDENTITY_PROVIDER }}
        service_account: ${{ vars.SERVICE_ACCOUNT }}

    - name: setup Packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: ${{ env.PRODUCT_VERSION }}
    - name: Run `packer init`
      id: init
      run: "packer init -var-file=winimage.example.pkrvars.hcl . "
    - name: Run `packer build`
      id: build
      run: "packer build -var-file=winimage.example.pkrvars.hcl . "