name: Build and Publish VM Image

on:
  push:
    branches:
      - main

env:
  PRODUCT_VERSION: "1.8.6"

jobs:
  build:
    runs-on: ubuntu-latest
    name: run packer
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ vars.WL_IDENTITY_PROVIDER }}
        service_account: ${{ vars.SERVICE_ACCOUNT }}

    - name: setup Packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: ${{ env.PRODUCT_VERSION }}